Revert "HDDS-11076. NoSuchMethodError: ByteBuffer.position compiling with Java 9+, running with Java 8 (#6897)"
This reverts commit 8f610da91f32ec9e8a124b6cbd211407f0290ca3.