HDDS-11076. NoSuchMethodError: ByteBuffer.position compiling with Java 9+, running with Java 8 (#6897)
(cherry picked from commit 8f610da91f32ec9e8a124b6cbd211407f0290ca3)